[tool.poetry]
name = "qtn_sim"
version = "0.1.0"
description = "My qtn_sim package v1!"
authors = ["Aadi Patwardhan"]
readme = "README.md"

    
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
dependencies = {file = ["requirements.txt"]}